# 一起来打怪之 Credit Scoring 练习

---
## 作业说明

- 答题步骤：
    - 回答问题**请保留每一步**操作过程，请不要仅仅给出最后答案
    - 请养成代码注释的好习惯

- 解题思路：
    - 为方便大家准确理解题目，在习题实战中有所收获，本文档提供了解题思路提示
    - 解题思路**仅供参考**，鼓励原创解题方法
    - 为督促同学们自己思考，解题思路内容设置为**白色**，必要时请从冒号后拖动鼠标查看

- 所用数据
    - 请注意导入数据库后先**查看和了解数据的基本性质**，后面的问题不再一一提醒

## machine learning for credit scoring


Banks play a crucial role in market economies. They decide who can get finance and on what terms and can make or break investment decisions. For markets and society to function, individuals and companies need access to credit. 

Credit scoring algorithms, which make a guess at the probability of default, are the method banks use to determine whether or not a loan should be granted. This competition requires participants to improve on the state of the art in credit scoring, by predicting the probability that somebody will experience financial distress in the next two years. [Dataset](https://www.kaggle.com/c/GiveMeSomeCredit)

Attribute Information:

|Variable Name	|	Description	|	Type|
|----|----|----|
|SeriousDlqin2yrs	|	Person experienced 90 days past due delinquency or worse 	|	Y/N|
|RevolvingUtilizationOfUnsecuredLines	|	Total balance on credit divided by the sum of credit limits	|	percentage|
|age	|	Age of borrower in years	|	integer|
|NumberOfTime30-59DaysPastDueNotWorse	|	Number of times borrower has been 30-59 days past due |	integer|
|DebtRatio	|	Monthly debt payments	|	percentage|
|MonthlyIncome	|	Monthly income	|	real|
|NumberOfOpenCreditLinesAndLoans	|	Number of Open loans |	integer|
|NumberOfTimes90DaysLate	|	Number of times borrower has been 90 days or more past due.	|	integer|
|NumberRealEstateLoansOrLines	|	Number of mortgage and real estate loans	|	integer|
|NumberOfTime60-89DaysPastDueNotWorse	|	Number of times borrower has been 60-89 days past due |integer|
|NumberOfDependents	|	Number of dependents in family	|	integer|


----------
## Read the data into Pandas 

In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)
import zipfile
with zipfile.ZipFile('KaggleCredit2.csv.zip', 'r') as z:
    f = z.open('KaggleCredit2.csv')
    data = pd.read_csv(f, index_col=0)
data.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines   age  \
0                 1                              0.766127  45.0   
1                 0                              0.957151  40.0   
2                 0                              0.658180  38.0   
3                 0                              0.233810  30.0   
4                 0                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [2]:
data.shape

(112915, 11)

------------
## Drop na

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 112915 entries, 0 to 112914
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype  
---  ------                                --------------   -----  
 0   SeriousDlqin2yrs                      112915 non-null  int64  
 1   RevolvingUtilizationOfUnsecuredLines  112915 non-null  float64
 2   age                                   108648 non-null  float64
 3   NumberOfTime30-59DaysPastDueNotWorse  112915 non-null  float64
 4   DebtRatio                             112915 non-null  float64
 5   MonthlyIncome                         112915 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       112915 non-null  float64
 7   NumberOfTimes90DaysLate               112915 non-null  float64
 8   NumberRealEstateLoansOrLines          112915 non-null  float64
 9   NumberOfTime60-89DaysPastDueNotWorse  112915 non-null  float64
 10  NumberOfDependents                    108648 non-null  float64
dtypes: fl

In [2]:
data.isnull().sum(axis=0)

SeriousDlqin2yrs                           0
RevolvingUtilizationOfUnsecuredLines       0
age                                     4267
NumberOfTime30-59DaysPastDueNotWorse       0
DebtRatio                                  0
MonthlyIncome                              0
NumberOfOpenCreditLinesAndLoans            0
NumberOfTimes90DaysLate                    0
NumberRealEstateLoansOrLines               0
NumberOfTime60-89DaysPastDueNotWorse       0
NumberOfDependents                      4267
dtype: int64

In [3]:
data.dropna(inplace=True)
data.shape

(108648, 11)

---------
## Create X and y

In [4]:
y = data['SeriousDlqin2yrs']
X = data.drop('SeriousDlqin2yrs', axis=1)

In [5]:
y.mean()

0.06742876076872101

---
## 练习1：把数据切分成训练集和测试集
- 提示：<span style='color:white'>from sklearn.model_selection import train_test_split('Gender') </span>

In [6]:
## your code here
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=0)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((76053, 10), (32595, 10), (76053,), (32595,))

In [7]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)

StandardScaler()

In [8]:
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

----
## 练习2：使用logistic regression/决策树/SVM/KNN...等sklearn分类算法进行分类
尝试查sklearn API了解模型参数含义，调整不同的参数

### Logistic regression
- 提示：<span style='color:white'>from sklearn import linear_model('Gender') </span>

In [11]:
## your code here
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=1000.0, max_iter=100, random_state=0)
lr.fit(X_train_std, y_train)

LogisticRegression(C=1000.0, random_state=0)

### Decision Tree
- 提示：<span style='color:white'>from sklearn.tree import DecisionTreeClassifier('Gender') </span>

In [12]:
## your code here
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)
tree.fit(X_train_std, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

### Random Forest
- 提示：<span style='color:white'>from sklearn.ensemble import RandomForestClassifier('Gender') </span>

In [13]:
## your code here
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=1, n_jobs=2)
forest.fit(X_train_std, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, n_jobs=2,
                       random_state=1)

### SVM
- 提示：<span style='color:white'>from sklearn.svm import SVC('Gender') </span>

In [14]:
## your code here
from sklearn.svm import SVC
#需要添加probability选项以方便后续调整决策边界
svm = SVC(kernel='linear', C=1.0, random_state=0, probability=True)
svm.fit(X_train_std, y_train)

SVC(kernel='linear', probability=True, random_state=0)

In [9]:
#由于训练时间太长，导出以备用
import joblib

# joblib.dump(svm, 'svm.pkl')
svm = joblib.load('svm.pkl')

### KNN
- 提示：<span style='color:white'>from sklearn.neighbors import KNeighborsClassifier('Gender') </span>

In [15]:
## your code here
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')
knn.fit(X_train_std, y_train)

KNeighborsClassifier()

---

## 练习3：在测试集上进行预测，计算准确度

### Logistic regression
- 提示：<span style='color:white'>y_pred_LR = clf_LR.predict(x_test)('Gender') </span>

In [16]:
## your code here
from sklearn.metrics import accuracy_score

y_pred_lr = lr.predict(X_test_std)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred_lr))

Accuracy: 0.93


### Decision Tree
- 提示：<span style='color:white'>y_pred_tree = tree.predict(x_test)('Gender') </span>

In [17]:
## your code here
y_pred_dt = tree.predict(X_test_std)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred_dt))

Accuracy: 0.94


### Random Forest
- 提示：<span style='color:white'>y_pred_forest = forest.predict(x_test)('Gender') </span>

In [18]:
## your code here
y_pred_rf = forest.predict(X_test_std)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred_rf))

Accuracy: 0.93


### SVM
- 提示：<span style='color:white'>y_pred_SVC = clf_svc.predict(x_test)('Gender') </span>

In [11]:
## your code here
y_pred_svm = svm.predict(X_test_std)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred_svm))

Accuracy: 0.93


### KNN
- 提示：<span style='color:white'>y_pred_KNN = neigh.predict(x_test)('Gender') </span>

In [20]:
## your code here
y_pred_knn = knn.predict(X_test_std)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred_knn))

Accuracy: 0.93


---
## 练习4：查看sklearn的官方说明，了解分类问题的评估标准，并对此例进行评估

**混淆矩阵（Confusion Matrix）相关学习链接**

- Blog:<br>
http://blog.csdn.net/vesper305/article/details/44927047<br>
- WiKi:<br>
http://en.wikipedia.org/wiki/Confusion_matrix<br>
- sklearn doc:<br>
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html

In [21]:
## your code here
#导入需要的包
from sklearn.metrics import confusion_matrix

#直接调用confusion_matrix依次查看混淆矩阵
print('Confusion matrix for logistic regression:')
print(confusion_matrix(y_test, y_pred_lr), end='\n\n')

print('Confusion matrix for decision tree:')
print(confusion_matrix(y_test, y_pred_dt), end='\n\n')

print('Confusion matrix for random forest:')
print(confusion_matrix(y_test, y_pred_rf), end='\n\n')

print('Confusion matrix for SVM:')
print(confusion_matrix(y_test, y_pred_svm), end='\n\n')

print('Confusion matrix for KNN:')
print(confusion_matrix(y_test, y_pred_knn), end='\n\n')

Confusion matrix for logistic regression:
[[30349    75]
 [ 2079    92]]

Confusion matrix for decision tree:
[[30104   320]
 [ 1798   373]]

Confusion matrix for random forest:
[[30084   340]
 [ 1853   318]]

Confusion matrix for SVM:
[[30406    18]
 [ 2151    20]]

Confusion matrix for KNN:
[[30141   283]
 [ 1922   249]]



In [22]:
#封装
model = ['logistic regression', 'decision tree', 'random forest', 'SVM', 'KNN']
pred_list = [y_pred_lr, y_pred_dt, y_pred_rf, y_pred_svm, y_pred_knn]

for i in range(len(pred_list)):
    print('Confusion matrix for %s:' % model[i])
    print(confusion_matrix(y_test, pred_list[i]), end='\n\n')

Confusion matrix for logistic regression:
[[30349    75]
 [ 2079    92]]

Confusion matrix for decision tree:
[[30104   320]
 [ 1798   373]]

Confusion matrix for random forest:
[[30084   340]
 [ 1853   318]]

Confusion matrix for SVM:
[[30406    18]
 [ 2151    20]]

Confusion matrix for KNN:
[[30141   283]
 [ 1922   249]]



## 练习5：调整模型的标准

银行通常会有更严格的要求，因为fraud带来的后果通常比较严重，一般我们会调整模型的标准。<br>

比如在logistic regression当中，一般我们的概率判定边界为0.5，但是我们可以把阈值设定低一些，来提高模型的“敏感度”，试试看把阈值设定为0.3，再看看这时的评估指标(主要是准确率和召回率)。

- 提示：<span style='color:white'>sklearn的很多分类模型，predict_prob可以拿到预估的概率，可以根据它和设定的阈值大小去判断最终结果(分类类别)('Gender') </span>

In [23]:
## your code here
#导入需要的包
import numpy as np

#查看一下判断的概率
print(lr.predict_proba(X_test_std), end='\n\n')
#按照新的阈值进行新的预测
pred_boun = 0.3
y_pred_lr_new = np.where(lr.predict_proba(X_test_std)[:,1] > pred_boun, 1, 0)
#对比混淆矩阵
print('Confusion matrix for logistic regression before:')
print(confusion_matrix(y_test, y_pred_lr))
print('Confusion matrix for logistic regression after:')
print(confusion_matrix(y_test, y_pred_lr_new))

[[0.96849652 0.03150348]
 [0.97693906 0.02306094]
 [0.94818194 0.05181806]
 ...
 [0.96155026 0.03844974]
 [0.94208568 0.05791432]
 [0.89507889 0.10492111]]

Confusion matrix for logistic regression before:
[[30349    75]
 [ 2079    92]]
Confusion matrix for logistic regression after:
[[30201   223]
 [ 1942   229]]


In [24]:
#对所有模型来一遍
model = ['logistic regression', 'decision tree', 'random forest', 'SVM', 'KNN']
pred_list = [y_pred_lr, y_pred_dt, y_pred_rf, y_pred_svm, y_pred_knn]
proba_list = [lr.predict_proba(X_test_std)[:,1], tree.predict_proba(X_test_std)[:,1], 
              forest.predict_proba(X_test_std)[:,1], svm.predict_proba(X_test_std)[:,1], 
              knn.predict_proba(X_test_std)[:,1]]
pred_list_new = []

for i in range(len(pred_list)):
    pred_list_new.append(np.where(proba_list[i] > pred_boun, 1, 0))
    print('Confusion matrix for %s before:' % model[i])
    print(confusion_matrix(y_test, pred_list[i]))
    print('Confusion matrix for %s after:' % model[i])
    print(confusion_matrix(y_test, pred_list_new[i]), end='\n\n')

Confusion matrix for logistic regression before:
[[30349    75]
 [ 2079    92]]
Confusion matrix for logistic regression after:
[[30201   223]
 [ 1942   229]]

Confusion matrix for decision tree before:
[[30104   320]
 [ 1798   373]]
Confusion matrix for decision tree after:
[[29948   476]
 [ 1660   511]]

Confusion matrix for random forest before:
[[30084   340]
 [ 1853   318]]
Confusion matrix for random forest after:
[[29321  1103]
 [ 1460   711]]

Confusion matrix for SVM before:
[[30406    18]
 [ 2151    20]]
Confusion matrix for SVM after:
[[30406    18]
 [ 2151    20]]

Confusion matrix for KNN before:
[[30141   283]
 [ 1922   249]]
Confusion matrix for KNN after:
[[29403  1021]
 [ 1614   557]]

