# 一起来打怪之 Credit Scoring 练习

---
## 作业说明

- 答题步骤：
    - 回答问题**请保留每一步**操作过程，请不要仅仅给出最后答案
    - 请养成代码注释的好习惯

- 解题思路：
    - 为方便大家准确理解题目，在习题实战中有所收获，本文档提供了解题思路提示
    - 解题思路**仅供参考**，鼓励原创解题方法
    - 为督促同学们自己思考，解题思路内容设置为**白色**，必要时请从冒号后拖动鼠标查看

- 所用数据
    - 请注意导入数据库后先**查看和了解数据的基本性质**，后面的问题不再一一提醒

## machine learning for credit scoring


Banks play a crucial role in market economies. They decide who can get finance and on what terms and can make or break investment decisions. For markets and society to function, individuals and companies need access to credit. 

Credit scoring algorithms, which make a guess at the probability of default, are the method banks use to determine whether or not a loan should be granted. This competition requires participants to improve on the state of the art in credit scoring, by predicting the probability that somebody will experience financial distress in the next two years. [Dataset](https://www.kaggle.com/c/GiveMeSomeCredit)

Attribute Information:

|Variable Name	|	Description	|	Type|
|----|----|----|
|SeriousDlqin2yrs	|	Person experienced 90 days past due delinquency or worse 	|	Y/N|
|RevolvingUtilizationOfUnsecuredLines	|	Total balance on credit divided by the sum of credit limits	|	percentage|
|age	|	Age of borrower in years	|	integer|
|NumberOfTime30-59DaysPastDueNotWorse	|	Number of times borrower has been 30-59 days past due |	integer|
|DebtRatio	|	Monthly debt payments	|	percentage|
|MonthlyIncome	|	Monthly income	|	real|
|NumberOfOpenCreditLinesAndLoans	|	Number of Open loans |	integer|
|NumberOfTimes90DaysLate	|	Number of times borrower has been 90 days or more past due.	|	integer|
|NumberRealEstateLoansOrLines	|	Number of mortgage and real estate loans	|	integer|
|NumberOfTime60-89DaysPastDueNotWorse	|	Number of times borrower has been 60-89 days past due |integer|
|NumberOfDependents	|	Number of dependents in family	|	integer|


----------
## Read the data into Pandas 

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500)

In [2]:
DataDictionary_path = "/home/Wangtl2022/PyProjects/Bootcamp/Data Dictionary.xls"
cs_test_path = "/home/Wangtl2022/PyProjects/Bootcamp/cs-test.csv"
cs_train_path = "/home/Wangtl2022/PyProjects/Bootcamp/cs-training.csv"
se_path = "/home/Wangtl2022/PyProjects/Bootcamp/sampleEntry.csv"

DataDictionary = pd.read_excel(DataDictionary_path)
cs_train = pd.read_csv(cs_train_path)
cs_test = pd.read_csv(cs_test_path)
se = pd.read_csv(se_path)

In [3]:
#!pip install xlrd

In [4]:
DataDictionary

Unnamed: 0  \
0                          Variable Name   
1                       SeriousDlqin2yrs   
2   RevolvingUtilizationOfUnsecuredLines   
3                                    age   
4   NumberOfTime30-59DaysPastDueNotWorse   
5                              DebtRatio   
6                          MonthlyIncome   
7        NumberOfOpenCreditLinesAndLoans   
8                NumberOfTimes90DaysLate   
9           NumberRealEstateLoansOrLines   
10  NumberOfTime60-89DaysPastDueNotWorse   
11                    NumberOfDependents   

                                           Unnamed: 1  Unnamed: 2  
0                                         Description        Type  
1   Person experienced 90 days past due delinquenc...         Y/N  
2   Total balance on credit cards and personal lin...  percentage  
3                            Age of borrower in years     integer  
4   Number of times borrower has been 30-59 days p...     integer  
5   Monthly debt payments, alimony,living costs di...  percentage  
6                                      Monthly income        real  
7   Number of Open loans (installment like car loa...     integer  
8   Number of times borrower has been 90 days or m...     integer  
9   Number of mortgage and real estate loans inclu...     integer  
10  Number of times borrower has been 60-89 days p...     integer  
11  Number of dependents in family excluding thems...     integer

In [5]:
cs_train

Unnamed: 0  SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  \
0                1                 1                              0.766127   
1                2                 0                              0.957151   
2                3                 0                              0.658180   
3                4                 0                              0.233810   
4                5                 0                              0.907239   
...            ...               ...                                   ...   
149995      149996                 0                              0.040674   
149996      149997                 0                              0.299745   
149997      149998                 0                              0.246044   
149998      149999                 0                              0.000000   
149999      150000                 0                              0.850283   

        age  NumberOfTime30-59DaysPastDueNotWorse    DebtRatio  MonthlyIncome  \
0        45                                     2     0.802982         9120.0   
1        40                                     0     0.121876         2600.0   
2        38                                     1     0.085113         3042.0   
3        30                                     0     0.036050         3300.0   
4        49                                     1     0.024926        63588.0   
...     ...                                   ...          ...            ...   
149995   74                                     0     0.225131         2100.0   
149996   44                                     0     0.716562         5584.0   
149997   58                                     0  3870.000000            NaN   
149998   30                                     0     0.000000         5716.0   
149999   64                                     0     0.249908         8158.0   

        NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                                    13                        0   
1                                     4                        0   
2                                     2                        1   
3                                     5                        0   
4                                     7                        0   
...                                 ...                      ...   
149995                                4                        0   
149996                                4                        0   
149997                               18                        0   
149998                                4                        0   
149999                                8                        0   

        NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                                  6                                     0   
1                                  0                                     0   
2                                  0                                     0   
3                                  0                                     0   
4                                  1                                     0   
...                              ...                                   ...   
149995                             1                                     0   
149996                             1                                     0   
149997                             1                                     0   
149998                             0                                     0   
149999                             2                                     0   

        NumberOfDependents  
0                      2.0  
1                      1.0  
2                      0.0  
3                      0.0  
4                      0.0  
...                    ...  
149995                 0.0  
149996                 2.0  
149997                 0.0  
149998                 0.0  
149999                 0.

In [6]:
se

Id  Probability
0            1     0.080807
1            2     0.040719
2            3     0.011968
3            4     0.067640
4            5     0.108264
...        ...          ...
101498  101499     0.045363
101499  101500     0.343775
101500  101501     0.006970
101501  101502     0.121994
101502  101503     0.044248

[101503 rows x 2 columns]

In [7]:
cs_test

Unnamed: 0  SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  \
0                1               NaN                              0.885519   
1                2               NaN                              0.463295   
2                3               NaN                              0.043275   
3                4               NaN                              0.280308   
4                5               NaN                              1.000000   
...            ...               ...                                   ...   
101498      101499               NaN                              0.282653   
101499      101500               NaN                              0.922156   
101500      101501               NaN                              0.081596   
101501      101502               NaN                              0.335457   
101502      101503               NaN                              0.441842   

        age  NumberOfTime30-59DaysPastDueNotWorse    DebtRatio  MonthlyIncome  \
0        43                                     0     0.177513         5700.0   
1        57                                     0     0.527237         9141.0   
2        59                                     0     0.687648         5083.0   
3        38                                     1     0.925961         3200.0   
4        27                                     0     0.019917         3865.0   
...     ...                                   ...          ...            ...   
101498   24                                     0     0.068522         1400.0   
101499   36                                     3     0.934217         7615.0   
101500   70                                     0   836.000000            NaN   
101501   56                                     0  3568.000000            NaN   
101502   29                                     0     0.198918         5916.0   

        NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                                     4                        0   
1                                    15                        0   
2                                    12                        0   
3                                     7                        0   
4                                     4                        0   
...                                 ...                      ...   
101498                                5                        0   
101499                                8                        0   
101500                                3                        0   
101501                                8                        0   
101502                               12                        0   

        NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                                  0                                     0   
1                                  4                                     0   
2                                  1                                     0   
3                                  2                                     0   
4                                  0                                     0   
...                              ...                                   ...   
101498                             0                                     0   
101499                             2                                     0   
101500                             0                                     0   
101501                             2                                     1   
101502                             0                                     0   

        NumberOfDependents  
0                      0.0  
1                      2.0  
2                      2.0  
3                      0.0  
4                      1.0  
...                    ...  
101498                 0.0  
101499                 4.0  
101500                 NaN  
101501                 3.0  
101502                 0.

In [8]:
cs_train = cs_train.drop(columns=["Unnamed: 0"])
#删除无用列

In [9]:
cs_test = cs_test.drop(columns=["Unnamed: 0","SeriousDlqin2yrs"])
#删除无用列和label列

------------
## Drop na

In [10]:
cs_train.isnull().sum(axis=0)

SeriousDlqin2yrs                            0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
dtype: int64

In [11]:
cs_test.isnull().sum(axis=0)

RevolvingUtilizationOfUnsecuredLines        0
age                                         0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome                           20103
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       2626
dtype: int64

In [12]:
cs_train.dropna(inplace=True)
cs_test.dropna(inplace=True)

In [13]:
cs_train.shape,cs_test.shape

((120269, 11), (81400, 10))

---------
## Create X and y

In [14]:
y =cs_train['SeriousDlqin2yrs']
X = cs_train.drop('SeriousDlqin2yrs', axis=1)

---
## 练习1：把数据切分成训练集和测试集
- 提示：<span style='color:white'>from sklearn.model_selection import train_test_split('Gender') </span>

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

----
## 练习2：使用logistic regression/决策树/SVM/KNN...等sklearn分类算法进行分类
尝试查sklearn API了解模型参数含义，调整不同的参数

### Logistic regression
- 提示：<span style='color:white'>from sklearn import linear_model('Gender') </span>

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
from sklearn.metrics import accuracy_score


lr = LogisticRegression(max_iter=200)
##迭代次数默认为100，结果显示不收敛(但acc=0.93)，因此调整为200.

lr.fit(X_train, y_train)

/usr/local/lib64/python3.6/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(max_iter=300)

### Decision Tree
- 提示：<span style='color:white'>from sklearn.tree import DecisionTreeClassifier('Gender') </span>

In [29]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier(random_state=42)

# 训练模型
DT.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

### Random Forest
- 提示：<span style='color:white'>from sklearn.ensemble import RandomForestClassifier('Gender') </span>

In [30]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(n_estimators = 1, max_depth = 1, random_state = 42)

RF.fit(X_train, y_train)

RandomForestClassifier(max_depth=1, n_estimators=1, random_state=42)

### SVM
- 提示：<span style='color:white'>from sklearn.svm import SVC('Gender') </span>

In [31]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

svc = SVC(kernel='linear', max_iter = 2000,random_state=42)  #收敛太慢，因此设置最大迭代次数

svc.fit(X_train, y_train)

/usr/local/lib64/python3.6/site-packages/sklearn/svm/_base.py:258: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(kernel='linear', max_iter=2000, random_state=42)

### KNN
- 提示：<span style='color:white'>from sklearn.neighbors import KNeighborsClassifier('Gender') </span>

In [32]:
from sklearn.neighbors import KNeighborsClassifier


knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred = model.predict(X_test)

---

## 练习3：在测试集上进行预测，计算准确度

### Logistic regression
- 提示：<span style='color:white'>y_pred_LR = clf_LR.predict(x_test)('Gender') </span>

In [36]:
from sklearn.metrics import accuracy_score

lr_pred = lr.predict(X_test)

accuracy = accuracy_score(y_test, lr_pred)
accuracy

0.9289515257337657

### Decision Tree
- 提示：<span style='color:white'>y_pred_tree = tree.predict(x_test)('Gender') </span>

In [37]:
dt_pred = DT.predict(X_test)

accuracy = accuracy_score(y_test, dt_pred)
accuracy

0.8903716637565477

### Random Forest
- 提示：<span style='color:white'>y_pred_forest = forest.predict(x_test)('Gender') </span>

In [38]:
rf_pred = RF.predict(X_test)

accuracy = accuracy_score(y_test, rf_pred)
accuracy

0.9294088301322025

### SVM
- 提示：<span style='color:white'>y_pred_SVC = clf_svc.predict(x_test)('Gender') </span>

In [39]:
svc_pred = svc.predict(X_test)

accuracy = accuracy_score(y_test, svc_pred)
accuracy

0.9244200548765278

### KNN
- 提示：<span style='color:white'>y_pred_KNN = neigh.predict(x_test)('Gender') </span>

In [40]:
knn_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, knn_pred)
accuracy

0.9278290513012388

---
## 练习4：查看sklearn的官方说明，了解分类问题的评估标准，并对此例进行评估

**混淆矩阵（Confusion Matrix）相关学习链接**

- Blog:<br>
http://blog.csdn.net/vesper305/article/details/44927047<br>
- WiKi:<br>
http://en.wikipedia.org/wiki/Confusion_matrix<br>
- sklearn doc:<br>
http://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html

In [44]:
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, lr_pred)
cm

array([[22300,    56],
       [ 1653,    45]])

In [45]:

cm = confusion_matrix(y_test, rf_pred)
cm

array([[22356,     0],
       [ 1698,     0]])

In [46]:

cm = confusion_matrix(y_test, svc_pred)
cm

array([[22235,   121],
       [ 1697,     1]])

In [47]:
cm = confusion_matrix(y_test, dt_pred)
cm

array([[20968,  1388],
       [ 1249,   449]])

In [48]:
cm = confusion_matrix(y_test, knn_pred)
cm

array([[22293,    63],
       [ 1673,    25]])

## 练习5：调整模型的标准

银行通常会有更严格的要求，因为fraud带来的后果通常比较严重，一般我们会调整模型的标准。<br>

比如在logistic regression当中，一般我们的概率判定边界为0.5，但是我们可以把阈值设定低一些，来提高模型的“敏感度”，试试看把阈值设定为0.3，再看看这时的评估指标(主要是准确率和召回率)。

- 提示：<span style='color:white'>sklearn的很多分类模型，predict_prob可以拿到预估的概率，可以根据它和设定的阈值大小去判断最终结果(分类类别)('Gender') </span>

In [49]:
lr_pred

array([0, 0, 0, ..., 0, 0, 0])

In [51]:
lr_pred_prob = lr.predict_proba(X_test)

In [53]:
lr_pred_prob

array([0.75683688, 0.24316312])

In [61]:
lr_pred_new = []

for i in lr_pred_prob:
    if i[0]>=0.3:
        lr_pred_new.append(0)
    else:
        lr_pred_new.append(1)

In [62]:
lr_pred_new = np.array(lr_pred_new)

In [63]:
from sklearn.metrics import precision_score, recall_score

#计算原来的recall和pre
pre = precision_score(y_test, lr_pred)

recall = recall_score(y_test, lr_pred)

#计算新的
pre_03 = precision_score(y_test, lr_pred_new)

recall_03 = recall_score(y_test, lr_pred_new)
pre,recall,pre_03,recall_03

(0.44554455445544555,
 0.026501766784452298,
 0.44680851063829785,
 0.012367491166077738)

In [64]:
#pre基本没变，但recall大幅下降。